using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace _13._11._2022
{
    internal class Class
    {
        static void Main(string[] args)
        {
            
            string s1, s2;

            s1 = "Hello World";
            s2 = "Hello";
            Console.WriteLine(s1.Contains(s2)); //Contains- return True is s1 contains s2 else False 

            char[] Copystring = new char[15];
            s1.CopyTo(0, Copystring, 0, s1.Length);
            Console.WriteLine(Copystring); //CopyTo- method will copied the count characters from the sourceIndex position to the destinationIndex position of destination character array.

            Console.WriteLine(s1.Insert(5, " Wonderful")); //Insert- return a new string in which a specified string is inserted at a specified index position in the current string instance.

            Console.WriteLine(s2.PadRight(10, '*')); //PadRight- left-aligns the characters in String by padding them with spaces or specified character on the right, for a specified total length. 

            Console.WriteLine(s1.Replace("World", "Friend")); //Replace- replace all the specified Unicode characters or specified string from the current string object and returns a new modified string.

            Console.WriteLine(s1.Substring(6)); //SubString- retrieve a substring from the current instance of the string.

            Copystring = s2.ToCharArray(2,2);
            Console.WriteLine(Copystring); //ToCharArray- copy the characters from a specified string in the current instance to a Unicode character array or the characters of a specified substring in the current instance to a Unicode character array 
            string s3="Ofer, Idan, Eden";
            string[] nameList=new string[7];
            char[] seperator = new char[6];
            seperator[0] = ',';
            seperator[1] = ' ';
            nameList = s3.Split(seperator);//Split- returns an array of strings generated by splitting of original string separated by the delimiters passed as a parameter
            foreach (string name in nameList)
                Console.WriteLine(name);

            s3 = "ofer123456";
            char[] charsToTrim1 = {'1', '2', '3', '4', '5','6'};
            Console.WriteLine(s3.Trim(charsToTrim1)); //Trim- removes all leading and trailing white-space characters from the current String object

            s3 = "12342331153ofer123456";
            Console.WriteLine(s3.TrimStart(charsToTrim1)); //TrimStart-  remove the occurrences of a set of characters specified in an array from the starting of the current String object.

            Console.WriteLine(s3.StartsWith("23")); //StartWith- check whether the beginning of the current string instance matches with a specified string or not.

            Console.WriteLine(s3.IndexOf('f')); //IndexOf- find the zero-based index of the first occurrence of a specified character or string within the current instance of the string.
            

            //Change SubString in String To Star-*
            string str1, str2, strChanged;
            str1 = "Hello to all friends, Hello to all people, Hello to all students";
            str2 = "Hello";
            strChanged=str1.Replace(str2, "*");
            str1 = strChanged;
            Console.WriteLine(str1);

            Console.ReadLine();
        }
    }
}
